name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-ios:
    runs-on: macos-latest

    steps:
      
      - uses: actions/checkout@v3.5.3
      - name: Install pods
        working-directory: ./iOS
        run: pod install --repo-update

      # - name: Run unit tests iOS 18
      #   working-directory: ./iOS
      #   run: |
      #     set -o pipefail
      #     sudo xcode-select -s '/Applications/Xcode_16.1.app/Contents/Developer'
      #     xcodebuild clean -workspace KaleyraVideoHybridNativeBridge.xcworkspace -scheme KaleyraVideoHybridNativeBridge | xcpretty
      #     xcodebuild test -workspace KaleyraVideoHybridNativeBridge.xcworkspace -scheme KaleyraVideoHybridNativeBridge -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=18.1"  | xcpretty -t

      - name: Run unit tests iOS 17
        working-directory: ./iOS
        run: |
          set -o pipefail
          sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
          xcodebuild clean -workspace KaleyraVideoHybridNativeBridge.xcworkspace -scheme KaleyraVideoHybridNativeBridge | xcpretty
          xcodebuild test -workspace KaleyraVideoHybridNativeBridge.xcworkspace -scheme KaleyraVideoHybridNativeBridge -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5"  | xcpretty -t

  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      # Execute unit tests
      - name: Unit Test
        working-directory: ./android
        run: ./gradlew testDebugUnitTest
