# Copyright © 2018-2023 Kaleyra S.p.a. All Rights Reserved.
# See LICENSE for licensing information

platform :ios, '15.0'

target 'KaleyraVideoHybridNativeBridge' do
  use_frameworks!

     pod 'KaleyraVideoSDK', '~> 4.2.0'

  target 'KaleyraVideoHybridNativeBridgeTests' do
    use_frameworks!

    pod 'SwiftHamcrest', '~> 2.2'
  end

end
