name: Release Module

on:
  workflow_dispatch:
    inputs:
      release_kind:
        type: choice
        description: What kind of release do you want to do?
        required: true
        options: 
        - 
        - patch
        - minor
        - major

jobs:
  release-module:
    runs-on: macos-latest
    environment:
      name: release_environment

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Setup
      uses: ./.github/actions/setup
    
    - name: Update package version
      run: npm run ${{ github.event.inputs.release_kind }}
      
    - name: Remove "private" constraint from package.json file
      run: |
        sed -i '' 's/\"private\": true/\"private\": false/g' package.json
        cat package.json
    
    - name: Publish to npm
      run: | 
        npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_API_KEY }}"
        npm publish
